export const CardSuits = {
  HEARTS: "♥",
  DIAMONDS: "♦",
  CLUBS: "♣",
  SPADES: "♠",
};

export const CardValues = [
  "A",
  "2",
  "3",
  "4",
  "5",
  "6",
  "7",
  "8",
  "9",
  "10",
  "J",
  "Q",
  "K",
];

export const GameEvents = {
  APP_INIT: "app:init",
  FULL_SCREEN_BTN: "full-screen-btn",
  BACK_BTN_CLICKED: "back:btn:clicked",
  STORAGE_SET: "storage:set",
  FIRST_CARD_CLICK: "first:card:click",
  START_PLAY_TIME: "start:play:time",
  STOP_PLAY_TIME: "stop:play:time",
  UIMANAGER_INIT: "uiManager:init",
  UINAMEPAGE_SHOW: "uiNamePage:show",
  UIMENUPAGE_SHOW: "uiMenuPage:show",
  UI_SETTINGS_SHOW: "ui:settings:show",
  UI_STATEPLAYER_SHOW: "ui:stateplayer:show",
  UI_SHOP_SHOW: "ui:shop:show",
  HINT_SHOW: 'hint:show',
  HINT_USED: 'hint:used',
  HINT_BTN_CLICK: 'hint:btn:click',
  HINT_NOTIF: 'hint:notif',
  UP_HITUSED_STATE: 'up:hintused:state',
  UI_NAME_HIDE: "ui:name:hide",
  UP_MOVES: "up:moves",
  UP_LAST_MOVE: "up:last:move",
  UP_ACHIEVENT_ICON: "up:achievement:icon",
  UP_ACHIEVENT_DIV: "up:achievement:div",
  UP_ACHIEVENT_SCORE_DIV: "up:achievement:score:div",
  RESET_LAST_MOVES: "reset:last:moves",
  RESET_ONPOINTERDOWN_TO_CARD: 'reset:onpointerdown:to:card',
  RESET_ONPOINTERMOVE_TO_CARD: 'reset:onpointermove:to:card',
  RESET_ONPOINTERUP_TO_CARD: 'reset:onpointerup:to:card',
  SET_NAME_IN_INPUT: "set:name:in:input",
  SET_ACTIV_PAGE: "set:activ:page",
  PLAYER_NAME_SET: "player:name:set",
  SET_SHOP_STATS: "set:shop:stats",
  END_SET_NEW_GAME: "end:set:new:game",
  SET_CURRENT_GAME: "set:current:game",
  SETTINGS_MUSIC_VOLUME: "settings:music:volume",
  SET_DIFFICUTY_CHANGE: "set:difficulty:change",
  SET_LANGUAGE_CHANGE: "set:language:change",
  SET_MUSIC_VOLUME: "set:music:volume",
  SET_SOUND_TOGGLE: "set:sound:toggle",
  SET_SELECTED_ITEMS: "set:selected:items",
  SET_NEW_GAME: "set:new:game",
  SET_CARDS_COMPONENTS: "set:cards:components",
  SET_CARD_DATA_ATTRIBUTE: "set:card:data:attribute",
  SET_DEALING_CARDS: 'set:dealing:cards',
  SET_ASSISTANCE_IN_COLLECTION: 'set:assistance:in:collection',
  GAME_NEW: "game:new",
  GAME_START: "game:start",
  GAME_CONTINUE: "game:continue",
  GAME_RESTART: "game:restart",
  GAME_PAUSE: "game:pause",
  GAME_EXIT: "game:exit",
  GAME_END: "game:end",
  GAME_WIN: "game:win",
  GAME_MOVE: "game:move",
  GAME_OVER: "game:over",
  HANDLE_WIN: "handle:win",
  ADD_CARD_CLICK: "add:card:click",
  ADD_ONPOINTERDOWN_TO_CARD: 'add:onpointerdown:to:card',
  ADD_ONPOINTERMOVE_TO_CARD: 'add:onpointermove:to:card',
  ADD_ONPOINTERUP_TO_CARD: 'add:onpointerup:to:card',
  ADD_POINTS: "add:points",
  CARD_CLICK: "card:clicked",
  CARD_FLIP: "card:flip",
  BACK_CARD_FLIP: "back:card:flip",
  AUDIO_CARD_FLIP: "audio:card:flip",
  AUDIO_CARD_MOVE: "audio:card:move",
  AUDIO_CARD_CLICK: "audio:card:click",
  AUDIO_UP_ACH: "audio:up:ach",
  AUDIO_UP_SCORE: "audio:up:score",
  UI_ANIMATION_POINTS_EARNED: "ui:animation:points:earned",
  UI_ANIMATE_WIN: "ui:animate:win",
  UI_ANIMATE_DEAL_CARDS: "ui:animate:deal:cards",
  CARD_TO_FOUNDATION: "card:to:foundation",
  CARD_TO_TABLEAU: "card:to:tableau",
  CARD_MOVED: "card:moved",
  CARD_MOVE: "card:move",
  UNDO_MOVE: "undo:move",
  ANIMATE_UNDO_TO_WASTE: "animate:undo:to:waste",
  CARD_MOVE_COMPLETED: "card:move:completed",
  STOCK_CLICK: "stock:click",
  SCORE_UPDATE: "game:score:update",
  TIME_UPDATE: "game:time:update",
  RENDER_CARDS: "render:cards",
  SHOP_BALANCE_UPDATE: "shop:balance:update",
  SHOW_ACH_DIV: "show:ach:div",
  INCREMENT_COINS: "increment:coins",
  DECREMENT_COINS: "decrement:coins",
  ANIMATION_COINS_EARNED: "animation:coins:earned",
  ANIMATE_STOCK_CARD_MOVE: "animate:stock:card:move",
  ANIMATE_CARD_TO_WASTE: "animate:card:to:waste",
  ANIMATE_CARD_MOVE: "animate:card:move",
  ANIMATE_CARD_WASTE_STOCK: "animate:card:waste:stock",
  SHOP_CATEGORY_CHANGE: "shop:category:change",
  SHOP_RENDER: "shop:render",
  UI_NOTIFICATION: "ui:notification",
  SHOP_ITEM_PURCHASE: "shop:item:purchase",
  GET_CARD_STYLES: "get:card:styles",
  GET_CARD_SOURCE: "get:card:source",
  COLLECT_BTN_SHOW: "collect:btn:show",
  IS_FACE_DOWN_CARD: "is:face:down:card",
  UP_FACE_DOWN_CARD: "up:face:down:card",
  PULSE_COLLECT_BTN: "pulse:collect:btn",
  CHANGE_CARDS_STYLES: "change:cards:styles",
  CARDS_COLLECT: "cards:collect",
  ADD_STOCK_EVENTS: "add:stock:events",
  COLLECT_BTN_HIDDEN: "collect:btn:hidden",
  UP_UNDO_CONTAINER: "up:undo:container",
  CHECK_GET_ACHIEVEMENTS: "check:get:achievements",
  CREAT_ELEMENT_FOR_HIGHEST_SCORE: 'creat:element:for:highest:score',
  CREAT_GAME_RESTART_MODAL: 'creat:game:restart:modal',
  BACK_MOVE_CARDS_TO_STOCK: 'back:move:cards:to:stock',
  SHUFFLE_CARDS_TO_STOCK: 'shuffle:cards:to:stock',
  CREAT_ELEMENT_FOR_NOTIF_SHUFFLED_CARDS: 'creat:element:for:notif:shuffled:cards',
  CREAT_ELEMENT_FOR_NOTIF_HINT_CARDS: 'creat:element:for:notif:hint:cards',
  GAME_RESULTS_MODAL_SHOW: 'game:results:modal:show',
  CHECK_AND_AUTO_MOVE: 'check:and:auto:move',
  CLEAR_NOTIF_HINT_CARDS: 'clear:notif:hint:cards',
  CREAT_ELEMENT_FOR_NOTIF_HINT_STOCK: 'creat:element:for:notif:hint:stock',
};

export const AnimationDurations = {
  WASTE_CARD_FLIP: 0.2,
  START_MOVE_SPEED: 50,
  CARD_STOCK_FLIP: 300,
  NOTIFICATION: 3000,
  CARD_MOVE: 300,
  CARD_FLIP: 200,
  FADE_IN: 250,
  FADE_OUT: 250,
};

export const AnimationDegs = {
  CARD_FLIP: 90,
  BACK_CARD_FLIP: -90,
};

export const AnimationOperators = {
  ADDITION: "+",
  SUBTRACTION: "-",
};

export const AudioName = {
  BACKGROUND: "background",
  CARD_FLIP: "card-flip",
  CARD_MOVE: "card-move",
  CLICK: "click",
  INFO: "info",
  WIN: "win",
  UP_SCORE: "up-score",
};
